# Generated by Django 4.2.5 on 2023-09-16 12:46

import app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.File)),
                ('profile', models.ImageField(blank=True, upload_to=app.models.File)),
                ('banner', models.ImageField(blank=True, upload_to=app.models.File)),
                ('bio_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActionUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.IntegerField()),
                ('price_asked', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
